name: reach_core
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  reach_research:
    path: /Users/fahad/AndroidStudioProjects/reach_research
  reach_auth:
    path: /Users/fahad/AndroidStudioProjects/reach_auth
  reach_chats:
    path: /Users/fahad/AndroidStudioProjects/reach_chats
  
  


  firebase_core: ^1.7.0

  cloud_firestore: ^2.5.3
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  font_awesome_flutter: 9.1.0
  flutter_material_pickers: 3.1.2
  flutter_riverpod: ^1.0.3
  url_launcher: 6.0.12
  get: ^4.6.5
  sizer: ^2.0.15
  equatable: ^2.0.5
  firebase_messaging: ^10.0.9

dev_dependencies:
  build_runner: 2.1.2 
  test: ^1.19.2
  # fake_cloud_firestore: any
  flutter_lints: any
  # flutter_test:
  #   sdk: flutter

  flutter_launcher_icons: 0.9.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
